# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/lab6_2_provided/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/lab6_2/lab6_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2 || ORIG_REF_NAME==lab6_2} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_microblaze_0_0/lab6_2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_microblaze_0_0 || ORIG_REF_NAME==lab6_2_microblaze_0_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_dlmb_v10_0/lab6_2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_dlmb_v10_0 || ORIG_REF_NAME==lab6_2_dlmb_v10_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_ilmb_v10_0/lab6_2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_ilmb_v10_0 || ORIG_REF_NAME==lab6_2_ilmb_v10_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_dlmb_bram_if_cntlr_0/lab6_2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab6_2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_ilmb_bram_if_cntlr_0/lab6_2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==lab6_2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_lmb_bram_0/lab6_2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_lmb_bram_0 || ORIG_REF_NAME==lab6_2_lmb_bram_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_xbar_0/lab6_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_xbar_0 || ORIG_REF_NAME==lab6_2_xbar_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_microblaze_0_axi_periph_0/lab6_2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==lab6_2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_microblaze_0_axi_intc_0/lab6_2_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==lab6_2_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_mdm_1_0/lab6_2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_mdm_1_0 || ORIG_REF_NAME==lab6_2_mdm_1_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_clk_wiz_1_0 || ORIG_REF_NAME==lab6_2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_rst_clk_wiz_1_100M_0/lab6_2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==lab6_2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_axi_gpio_0_0/lab6_2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_axi_gpio_0_0 || ORIG_REF_NAME==lab6_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_axi_gpio_0_1/lab6_2_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_axi_gpio_0_1 || ORIG_REF_NAME==lab6_2_axi_gpio_0_1} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_axi_gpio_1_0/lab6_2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_axi_gpio_1_0 || ORIG_REF_NAME==lab6_2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_axi_uartlite_0_0/lab6_2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_axi_uartlite_0_0 || ORIG_REF_NAME==lab6_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_axi_timer_0_0/lab6_2_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_axi_timer_0_0 || ORIG_REF_NAME==lab6_2_axi_timer_0_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_axi_quad_spi_0_0/lab6_2_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_axi_quad_spi_0_0 || ORIG_REF_NAME==lab6_2_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/lab6_2/ip/lab6_2_xlconcat_0_0/lab6_2_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab6_2_xlconcat_0_0 || ORIG_REF_NAME==lab6_2_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/lab6_2_ooc.xdc
