# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.srcs/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0.xci
# IP: The module: 'lab6_2_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab6_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab6_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab6_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.srcs/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0.xci
# IP: The module: 'lab6_2_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab6_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab6_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab 6/Lab_6_2/Lab_6_2.gen/sources_1/bd/lab6_2/ip/lab6_2_clk_wiz_1_0/lab6_2_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab6_2_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
