# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab7_2_provided_sp24/mb_usb_hdmi_top.xdc

# Block Designs: bd/Lab7_2/Lab7_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2 || ORIG_REF_NAME==Lab7_2} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_microblaze_0_0/Lab7_2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_microblaze_0_0 || ORIG_REF_NAME==Lab7_2_microblaze_0_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_dlmb_v10_0/Lab7_2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_dlmb_v10_0 || ORIG_REF_NAME==Lab7_2_dlmb_v10_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_ilmb_v10_0/Lab7_2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_ilmb_v10_0 || ORIG_REF_NAME==Lab7_2_ilmb_v10_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_dlmb_bram_if_cntlr_0/Lab7_2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab7_2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_ilmb_bram_if_cntlr_0/Lab7_2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab7_2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_lmb_bram_0/Lab7_2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_lmb_bram_0 || ORIG_REF_NAME==Lab7_2_lmb_bram_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_xbar_0/Lab7_2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_xbar_0 || ORIG_REF_NAME==Lab7_2_xbar_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_microblaze_0_axi_periph_0/Lab7_2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Lab7_2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_microblaze_0_axi_intc_0/Lab7_2_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Lab7_2_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_mdm_1_0/Lab7_2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_mdm_1_0 || ORIG_REF_NAME==Lab7_2_mdm_1_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_clk_wiz_1_0/Lab7_2_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_clk_wiz_1_0 || ORIG_REF_NAME==Lab7_2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_rst_clk_wiz_1_100M_0/Lab7_2_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Lab7_2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_axi_uartlite_0_0/Lab7_2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_axi_uartlite_0_0 || ORIG_REF_NAME==Lab7_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Lab7_2/ip/Lab7_2_hdmi_text_controller_0_0/Lab7_2_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_2_hdmi_text_controller_0_0 || ORIG_REF_NAME==Lab7_2_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab7_2/Lab7_2/Lab7_2.gen/sources_1/bd/Lab7_2/Lab7_2_ooc.xdc
