# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/14435/Desktop/ECE385/Lab7_2/Lab7_2/Lab7_2.srcs/sources_1/bd/Lab7_2/ip/Lab7_2_xbar_0/Lab7_2_xbar_0.xci
# IP: The module: 'Lab7_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Lab7_2/Lab7_2/Lab7_2.gen/sources_1/bd/Lab7_2/ip/Lab7_2_xbar_0/Lab7_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7_2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/14435/Desktop/ECE385/Lab7_2/Lab7_2/Lab7_2.srcs/sources_1/bd/Lab7_2/ip/Lab7_2_xbar_0/Lab7_2_xbar_0.xci
# IP: The module: 'Lab7_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Lab7_2/Lab7_2/Lab7_2.gen/sources_1/bd/Lab7_2/ip/Lab7_2_xbar_0/Lab7_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7_2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
