# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/14435/Desktop/ECE385/Lab7_1/Lab7_1/Lab7_1.srcs/sources_1/bd/Lab7_1/ip/Lab7_1_ilmb_bram_if_cntlr_0/Lab7_1_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Lab7_1_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Lab7_1/Lab7_1/Lab7_1.gen/sources_1/bd/Lab7_1/ip/Lab7_1_ilmb_bram_if_cntlr_0/Lab7_1_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7_1_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/14435/Desktop/ECE385/Lab7_1/Lab7_1/Lab7_1.srcs/sources_1/bd/Lab7_1/ip/Lab7_1_ilmb_bram_if_cntlr_0/Lab7_1_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'Lab7_1_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Lab7_1/Lab7_1/Lab7_1.gen/sources_1/bd/Lab7_1/ip/Lab7_1_ilmb_bram_if_cntlr_0/Lab7_1_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab7_1_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
