# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/14435/Desktop/ECE385/Final Project/Final Project/Final Project.srcs/sources_1/ip/blk_mem_gen_OV/blk_mem_gen_OV.xci
# IP: The module: 'blk_mem_gen_OV' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Final Project/Final Project/Final Project.gen/sources_1/ip/blk_mem_gen_OV/blk_mem_gen_OV_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_OV'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/14435/Desktop/ECE385/Final Project/Final Project/Final Project.srcs/sources_1/ip/blk_mem_gen_OV/blk_mem_gen_OV.xci
# IP: The module: 'blk_mem_gen_OV' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14435/Desktop/ECE385/Final Project/Final Project/Final Project.gen/sources_1/ip/blk_mem_gen_OV/blk_mem_gen_OV_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_OV'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
