# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# Block Designs: bd/Final_mb/Final_mb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb || ORIG_REF_NAME==Final_mb} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_microblaze_0_0/Final_mb_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_microblaze_0_0 || ORIG_REF_NAME==Final_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_dlmb_v10_0/Final_mb_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_dlmb_v10_0 || ORIG_REF_NAME==Final_mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_ilmb_v10_0/Final_mb_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_ilmb_v10_0 || ORIG_REF_NAME==Final_mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_dlmb_bram_if_cntlr_0/Final_mb_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Final_mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_ilmb_bram_if_cntlr_0/Final_mb_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Final_mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_lmb_bram_0/Final_mb_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_lmb_bram_0 || ORIG_REF_NAME==Final_mb_lmb_bram_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_xbar_0/Final_mb_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_xbar_0 || ORIG_REF_NAME==Final_mb_xbar_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_microblaze_0_axi_periph_0/Final_mb_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Final_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_microblaze_0_axi_intc_0/Final_mb_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Final_mb_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_microblaze_0_xlconcat_0/Final_mb_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Final_mb_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_mdm_1_0/Final_mb_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_mdm_1_0 || ORIG_REF_NAME==Final_mb_mdm_1_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_clk_wiz_1_0/Final_mb_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_clk_wiz_1_0 || ORIG_REF_NAME==Final_mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_rst_clk_wiz_1_100M_0/Final_mb_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Final_mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_axi_uartlite_0_0/Final_mb_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_axi_uartlite_0_0 || ORIG_REF_NAME==Final_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_axi_timer_0_0/Final_mb_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_axi_timer_0_0 || ORIG_REF_NAME==Final_mb_axi_timer_0_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_axi_gpio_0_0/Final_mb_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_axi_gpio_0_0 || ORIG_REF_NAME==Final_mb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_axi_gpio_0_1/Final_mb_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_axi_gpio_0_1 || ORIG_REF_NAME==Final_mb_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_axi_gpio_0_2/Final_mb_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_axi_gpio_0_2 || ORIG_REF_NAME==Final_mb_axi_gpio_0_2} -quiet] -quiet

# IP: bd/Final_mb/ip/Final_mb_axi_quad_spi_0_0/Final_mb_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Final_mb_axi_quad_spi_0_0 || ORIG_REF_NAME==Final_mb_axi_quad_spi_0_0} -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Final Project/Final Project/Final Project.gen/sources_1/bd/Final_mb/Final_mb_ooc.xdc
