# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/14435/Desktop/ECE385/Lab7_1/lab7_1_provided_sp24/mb_usb_hdmi_top.xdc

# Block Designs: bd/Lab7_1/Lab7_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1 || ORIG_REF_NAME==Lab7_1} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_microblaze_0_0/Lab7_1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_microblaze_0_0 || ORIG_REF_NAME==Lab7_1_microblaze_0_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_dlmb_v10_0/Lab7_1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_dlmb_v10_0 || ORIG_REF_NAME==Lab7_1_dlmb_v10_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_ilmb_v10_0/Lab7_1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_ilmb_v10_0 || ORIG_REF_NAME==Lab7_1_ilmb_v10_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_dlmb_bram_if_cntlr_0/Lab7_1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab7_1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_ilmb_bram_if_cntlr_0/Lab7_1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab7_1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_lmb_bram_0/Lab7_1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_lmb_bram_0 || ORIG_REF_NAME==Lab7_1_lmb_bram_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_xbar_0/Lab7_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_xbar_0 || ORIG_REF_NAME==Lab7_1_xbar_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_microblaze_0_axi_periph_0/Lab7_1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Lab7_1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_microblaze_0_axi_intc_0/Lab7_1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Lab7_1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_mdm_1_0/Lab7_1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_mdm_1_0 || ORIG_REF_NAME==Lab7_1_mdm_1_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_clk_wiz_1_0/Lab7_1_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_clk_wiz_1_0 || ORIG_REF_NAME==Lab7_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_rst_clk_wiz_1_100M_0/Lab7_1_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Lab7_1_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_axi_uartlite_0_0/Lab7_1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_axi_uartlite_0_0 || ORIG_REF_NAME==Lab7_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Lab7_1/ip/Lab7_1_hdmi_text_controller_0_0/Lab7_1_hdmi_text_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab7_1_hdmi_text_controller_0_0 || ORIG_REF_NAME==Lab7_1_hdmi_text_controller_0_0} -quiet] -quiet

# XDC: c:/Users/14435/Desktop/ECE385/Lab7_1/Lab7_1/Lab7_1.gen/sources_1/bd/Lab7_1/Lab7_1_ooc.xdc
